version: "3.7"

services:
  thelibrary:
    image: thelibrary
    ports:
      - "8000:8000"
    environment:
        - ENV_FILE=/thelibrary/dev_secrets.env
    entrypoint: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./src/:/thelibrary/
      - ./dev_secrets.env:/thelibrary/dev_secrets.env
      - ./staticfiles/:/static/
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: thelibrarypsw
      POSTGRES_USER: thelibraryuser
      POSTGRES_DB: thelibrarydb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/data/:/var/lib/postgresql/data/
